#!/usr/bin/env python3
"""
3D Filament Profiles - automatic print logging post-processing script.
https://3dfilamentprofiles.com/help/automatic-print-logging

Install (Bambu Studio / OrcaSlicer / PrusaSlicer and other PrusaSlicer forks):
  Print Settings -> Others -> Post-processing scripts (PrusaSlicer: Print
  Settings -> Output options), add a line like:
    "path/to/python" "path/to/3dfp-print-log.py"
  Options may go before the script's own arguments:
    --no-ask         skip the "Log this print?" dialog and open the browser straight away
    --base-url URL   send to a different site (dev/staging)
    --dry-run        print the URL instead of opening the browser
    --debug          write argv/env/gcode header to ~/3dfp-print-log-debug.txt

Bambu Studio 2.x runs post-processing scripts as soon as a plate is sliced,
so the script asks "Log this print?" first (native dialog, no extra install);
Skip and nothing happens. Pass --no-ask to always open the browser instead.
Older Bambu Studio versions only ran them on File -> Export -> Export G-code
(bambulab/BambuStudio#3006). OrcaSlicer runs them on export; if yours doesn't
run them on Send, use Export G-code.

What it does: takes the filament type/vendor/colour and printer from the
SLIC3R_* environment variables the slicer sets, reads the .gcode header for
what the slice actually used (grams, which slots, print time), and opens
your browser at <site>/my/print/log with that data in the URL. Sign in there
once and pick which spool each filament came from; the site does the actual
parsing and math. This script stays dumb on purpose, so it rarely needs to
change even as the site's parsing improves. In Bambu Studio it also picks up
the real project (3MF) name and, on re-slices, the plate.

Nothing else in the file is read. No gcode, no toolpaths, no design content
leaves your machine - only the handful of comment lines listed in
LINE_PREFIXES below, capped at MAX_PAYLOAD_BYTES.

Always exits 0 and prints problems to stderr, so a failure here can never
break your slicer's export.
"""

from __future__ import annotations

import base64
import os
import sys
import webbrowser
from urllib.parse import quote

VERSION = "1.0.0"

DEFAULT_BASE_URL = "https://3dfilamentprofiles.com"

# Kept in sync with the regexes in src/app/[locale]/my/print/parseGCodeFilaments.ts
# and src/app/[locale]/my/print/log/decodePrintLogPayload.ts. Matching is by
# prefix, so order here doesn't matter for extraction (it does for the output,
# to keep the payload stable and readable).
LINE_PREFIXES = (
    "; filament used [g]",
    "; filament used [mm]",
    "; total filament weight [g]",
    "; total filament length [mm]",
    "; total filament used [g]",
    "; filament:",  # Bambu Studio: which slots the plate uses, e.g. "; filament: 2" or "; filament: 1,3"
    "; filament_type =",
    "; filament_vendor =",
    "; filament_colour =",
    "; filament_settings_id =",
    "; printer_model =",
    "; printer_settings_id =",
    "; estimated printing time",
    "; model printing time",
    "; generated by",
    "; BambuStudio",
    "; OrcaSlicer",
    "; PrusaSlicer",
)

# Config values PrusaSlicer-family slicers (PrusaSlicer, OrcaSlicer, Bambu Studio, ...)
# also export to post-processing scripts as SLIC3R_<KEY> environment variables. Taking
# them from the environment means the gcode itself only has to be read up to its header
# (grams used, which slots were used, print time), not all the way to the config block
# at the end of a multi-megabyte file.
ENV_CONFIG_KEYS = (
    "filament_type",
    "filament_vendor",
    "filament_colour",
    "filament_settings_id",
    "printer_model",
    "printer_settings_id",
)

MAX_LINE_LENGTH = 400
MAX_PAYLOAD_BYTES = 16 * 1024


def lines_from_env() -> dict[str, str]:
    """Rebuilds '; key = value' config lines from SLIC3R_* env vars, when the slicer set them."""
    found: dict[str, str] = {}
    for key in ENV_CONFIG_KEYS:
        value = os.environ.get(f"SLIC3R_{key.upper()}")
        if value:
            found[f"; {key} ="] = f"; {key} = {value}"[:MAX_LINE_LENGTH]
    return found


def extract_lines(gcode_path: str) -> list[str]:
    """Keeps the first line matching each allow-listed prefix, truncated to MAX_LINE_LENGTH."""
    found: dict[str, str] = lines_from_env()
    have_env_config = len(found) > 0
    with open(gcode_path, "r", encoding="utf-8", errors="replace") as gcode_file:
        for raw_line in gcode_file:
            line = raw_line.rstrip("\r\n")
            for prefix in LINE_PREFIXES:
                if prefix in found:
                    continue
                if line.startswith(prefix):
                    found[prefix] = line[:MAX_LINE_LENGTH]
            if len(found) == len(LINE_PREFIXES):
                break  # every line we care about has been seen; no need to read the rest.
            # With config from the environment, only the header matters. Bambu Studio and
            # OrcaSlicer put the usage summary in the header block; PrusaSlicer puts it at
            # the end, so only stop early once a weight line has actually been seen.
            if (
                have_env_config
                and line.startswith("; HEADER_BLOCK_END")
                and any(prefix in found for prefix in ("; filament used [g]", "; total filament weight [g]"))
            ):
                break
    return [found[prefix] for prefix in LINE_PREFIXES if prefix in found]


class BambuProject:
    """What Bambu Studio's temp project folder tells us; every field is optional."""

    def __init__(self) -> None:
        self.project_name: str | None = None
        self.plate_index: str | None = None
        self.plate_name: str | None = None
        # All plates in the project as (index, name), for the page's plate picker when
        # the sliced plate itself could not be determined.
        self.plates: list[tuple[str, str]] = []


def find_bambu_project(gcode_path: str) -> BambuProject:
    """
    Bambu Studio slices into a temp project folder and hands us a throwaway path like
    <tmp>/bamboo_model/<date>/<time#pid#n>/Metadata/.<pid>.<n>.gcode. That folder holds:
      - origin.txt: the path of the 3MF the user actually opened (the real project name)
      - .3mf: an autosave whose Metadata/model_settings.config lists the plates
        (plater_id, plater_name) and maps each to its temp gcode_file.
    The plate mapping is written by Bambu Studio one step behind the slice, so it is only
    present when a plate is re-sliced; on a first slice we can still offer the plate list.
    """
    info = BambuProject()
    folder = os.path.dirname(os.path.abspath(gcode_path))
    for _ in range(3):
        origin_txt = os.path.join(folder, "origin.txt")
        if os.path.isfile(origin_txt):
            break
        parent = os.path.dirname(folder)
        if parent == folder:
            return info
        folder = parent
    else:
        return info

    try:
        with open(origin_txt, "r", encoding="utf-8", errors="replace") as origin_file:
            origin_path = origin_file.read().strip()
        info.project_name = os.path.basename(origin_path) or None
    except OSError:
        pass

    autosave = os.path.join(folder, ".3mf")
    if os.path.isfile(autosave):
        try:
            import re
            import zipfile

            with zipfile.ZipFile(autosave) as archive:
                settings = archive.read("Metadata/model_settings.config").decode("utf-8", errors="replace")
            wanted = os.path.basename(gcode_path)
            for plate_block in re.findall(r"<plate>(.*?)</plate>", settings, flags=re.DOTALL):
                plate_id = re.search(r'key="plater_id" value="([^"]*)"', plate_block)
                name = re.search(r'key="plater_name" value="([^"]*)"', plate_block)
                gcode_file = re.search(r'key="gcode_file" value="([^"]*)"', plate_block)
                if not plate_id:
                    continue
                plate_name = name.group(1) if name else ""
                info.plates.append((plate_id.group(1), plate_name))
                if gcode_file and os.path.basename(gcode_file.group(1)) == wanted:
                    info.plate_index = plate_id.group(1)
                    info.plate_name = plate_name or None
        except Exception as err:  # optional nicety; never block the export over it
            print(f"3dfp-print-log: could not read plate info: {err}", file=sys.stderr)

    return info


def total_grams(lines: list[str]) -> float | None:
    """Sums the per-filament weights from the usage line, for the confirmation dialog only."""
    import re

    for line in lines:
        match = re.match(r"^; (?:total filament weight \[g\] :|filament used \[g\] =) ([\d.,\s]+)$", line)
        if match:
            try:
                return sum(float(part) for part in match.group(1).split(",") if part.strip())
            except ValueError:
                return None
    return None


def build_url(base_url: str, gcode_path: str) -> tuple[str | None, str]:
    """Returns (url, one-line summary for the confirmation dialog). url is None when there is nothing to log."""
    lines = extract_lines(gcode_path)
    if not lines:
        print("3dfp-print-log: no recognizable filament usage comments found, skipping.", file=sys.stderr)
        return None, ""

    payload = "\n".join(lines).encode("utf-8")
    if len(payload) > MAX_PAYLOAD_BYTES:
        payload = payload[:MAX_PAYLOAD_BYTES]

    encoded = base64.urlsafe_b64encode(payload).decode("ascii").rstrip("=")

    project = find_bambu_project(gcode_path)
    file_name = project.project_name or os.path.basename(gcode_path)

    query = f"v=1&f={quote(file_name)}"
    if project.plate_index:
        query += f"&p={quote(project.plate_index)}"
        if project.plate_name:
            query += f"&pn={quote(project.plate_name)}"
    elif project.plates:
        query += "&pl=" + quote("|".join(f"{index}:{name}" for index, name in project.plates[:20]))
    query += f"&d={encoded}"

    summary = file_name
    if project.plate_index:
        summary += f", plate {project.plate_index}"
        if project.plate_name:
            summary += f" ({project.plate_name})"
    grams = total_grams(lines)
    if grams is not None:
        summary += f", {grams:.1f} g"

    return f"{base_url.rstrip('/')}/my/print/log?{query}", summary


DIALOG_TIMEOUT_SECONDS = 60


def ask_user(summary: str) -> bool:
    """
    Native yes/no dialog with no third-party dependencies: AppleScript on macOS, MessageBox on
    Windows, zenity/tkinter on Linux. Returns True to open the browser. Any failure, or no
    answer within DIALOG_TIMEOUT_SECONDS, is treated as "yes" so an unattended slice still
    just opens a tab (the old behaviour) instead of silently dropping the print.
    """
    import subprocess

    title = "3D Filament Profiles"
    text = f"Log this print?\n\n{summary}"
    try:
        if sys.platform == "darwin":
            script = (
                f'display dialog {_applescript_string(text)} with title {_applescript_string(title)} '
                f'buttons {{"Skip", "Log it"}} default button "Log it" cancel button "Skip" '
                f"giving up after {DIALOG_TIMEOUT_SECONDS}"
            )
            result = subprocess.run(["osascript", "-e", script], capture_output=True, text=True, timeout=DIALOG_TIMEOUT_SECONDS + 5)
            # Cancel button -> exit code 1 (user cancelled); "gave up:true" -> timeout -> open anyway.
            return result.returncode == 0
        if sys.platform == "win32":
            import ctypes

            MB_YESNO, MB_ICONQUESTION, MB_SETFOREGROUND, MB_TOPMOST = 0x4, 0x20, 0x10000, 0x40000
            IDYES = 6
            user32 = ctypes.windll.user32  # type: ignore[attr-defined]
            try:
                # Undocumented but long-stable; lets the dialog time out. 32000 = timeout result.
                answer = user32.MessageBoxTimeoutW(
                    None, text, title, MB_YESNO | MB_ICONQUESTION | MB_SETFOREGROUND | MB_TOPMOST, 0, DIALOG_TIMEOUT_SECONDS * 1000
                )
                return answer in (IDYES, 32000)
            except AttributeError:
                answer = user32.MessageBoxW(None, text, title, MB_YESNO | MB_ICONQUESTION | MB_SETFOREGROUND | MB_TOPMOST)
                return answer == IDYES
        # Linux / other: zenity if present, else tkinter, else just go ahead.
        try:
            result = subprocess.run(
                ["zenity", "--question", f"--title={title}", f"--text={text}", "--ok-label=Log it", "--cancel-label=Skip",
                 f"--timeout={DIALOG_TIMEOUT_SECONDS}"],
                capture_output=True, timeout=DIALOG_TIMEOUT_SECONDS + 5,
            )
            return result.returncode in (0, 5)  # 5 = timeout
        except FileNotFoundError:
            pass
        try:
            import tkinter
            from tkinter import messagebox

            root = tkinter.Tk()
            root.withdraw()
            root.after(DIALOG_TIMEOUT_SECONDS * 1000, root.destroy)
            answer = messagebox.askyesno(title, text, parent=root)
            return bool(answer)
        except Exception:
            return True
    except Exception as err:
        print(f"3dfp-print-log: dialog failed, opening browser anyway: {err}", file=sys.stderr)
        return True


def _applescript_string(value: str) -> str:
    return '"' + value.replace("\\", "\\\\").replace('"', '\\"').replace("\n", "\\n") + '"'


def write_debug_dump(argv: list[str], gcode_path: str) -> None:
    """Writes argv, slicer-provided env vars and the gcode header/config keys to ~/3dfp-print-log-debug.txt."""
    dump_path = os.path.join(os.path.expanduser("~"), "3dfp-print-log-debug.txt")
    with open(dump_path, "w", encoding="utf-8") as out:
        out.write(f"3dfp-print-log {VERSION}\nargv: {argv!r}\ncwd: {os.getcwd()}\n\n== env ==\n")
        for key in sorted(os.environ):
            if key.upper().startswith(("SLIC3R", "BAMBU", "ORCA", "PRUSA")):
                out.write(f"{key}={os.environ[key][:400]}\n")
        out.write("\n== gcode comment lines (first 60 + config block keys) ==\n")
        try:
            comment_lines: list[str] = []
            config_keys: list[str] = []
            in_config = False
            with open(gcode_path, "r", encoding="utf-8", errors="replace") as gcode_file:
                for raw_line in gcode_file:
                    line = raw_line.rstrip("\r\n")
                    if line.startswith("; CONFIG_BLOCK_START"):
                        in_config = True
                    if in_config and line.startswith("; ") and " = " in line:
                        config_keys.append(line[2:].split(" = ", 1)[0])
                    elif line.startswith(";") and len(comment_lines) < 60:
                        comment_lines.append(line[:300])
            out.write("\n".join(comment_lines))
            out.write("\n\n== config keys ==\n" + ", ".join(config_keys) + "\n")
        except OSError as err:
            out.write(f"could not read gcode: {err}\n")
    print(f"3dfp-print-log: debug dump written to {dump_path}", file=sys.stderr)


def main(argv: list[str]) -> int:
    # Slicers append the gcode path as the LAST argument, so any options can be written
    # before it in the slicer's post-processing line, e.g.
    #   "python3" "3dfp-print-log.py" --no-ask --base-url http://localhost:3000
    args = argv[1:]
    dry_run = "--dry-run" in args
    debug = "--debug" in args
    ask = "--no-ask" not in args
    base_url = os.environ.get("FILAMENT_PROFILES_URL", DEFAULT_BASE_URL)
    if "--base-url" in args:
        idx = args.index("--base-url")
        if idx + 1 < len(args):
            base_url = args[idx + 1]
            del args[idx : idx + 2]
    args = [arg for arg in args if arg not in ("--dry-run", "--debug", "--no-ask")]

    if not args:
        print("3dfp-print-log: no gcode file given, skipping.", file=sys.stderr)
        return 0

    gcode_path = args[-1]
    if debug:
        try:
            write_debug_dump(argv, gcode_path)
        except Exception as err:  # debug output must never break the export either
            print(f"3dfp-print-log: debug dump failed: {err}", file=sys.stderr)

    try:
        url, summary = build_url(base_url, gcode_path)
    except OSError as err:
        print(f"3dfp-print-log: could not read '{gcode_path}': {err}", file=sys.stderr)
        return 0

    if not url:
        return 0

    if dry_run:
        print(url)
        return 0

    if ask and not ask_user(summary):
        return 0

    try:
        webbrowser.open(url)
    except Exception as err:  # never let a browser-launch failure break the slicer's export
        print(f"3dfp-print-log: could not open browser: {err}", file=sys.stderr)

    return 0


if __name__ == "__main__":
    sys.exit(main(sys.argv))
