<#
3D Filament Profiles - automatic print logging post-processing script (Windows, PowerShell).
https://3dfilamentprofiles.com/help/automatic-print-logging
Source, README and issues: https://github.com/MarksMakerSpace/filament-profiles/tree/main/tools/slicer-print-log

This is the Windows PowerShell version of 3dfp-print-log.py. Nothing to install:
powershell.exe ships with every Windows install at a path that never changes.

Install (Bambu Studio / OrcaSlicer / PrusaSlicer and other PrusaSlicer forks):
  Print Settings -> Others -> Post-processing scripts (PrusaSlicer: Print
  Settings -> Output options), add a line like:
    "C:\Windows\System32\WindowsPowerShell\v1.0\powershell.exe" -ExecutionPolicy Bypass -File "C:\path\to\3dfp-print-log.ps1"
  Options may go after the script path:
    --no-ask         skip the "Log this print?" dialog and open the browser straight away
    --base-url URL   send to a different site (dev/staging)
    --dry-run        print the URL instead of opening the browser
    --debug          write argv/env/gcode header to ~\3dfp-print-log-debug.txt

What it does: takes the filament type/vendor/colour and printer from the
SLIC3R_* environment variables the slicer sets, reads the .gcode header for
what the slice actually used (grams, which slots, print time), and opens
your browser at <site>/my/print/log with that data in the URL. Sign in there
once and pick which spool each filament came from; the site does the actual
parsing and math. In Bambu Studio it also picks up the real project (3MF)
name and, on re-slices, the plate.

Nothing else in the file is read. No gcode, no toolpaths, no design content
leaves your machine - only the handful of comment lines listed in
$LinePrefixes below, capped at $MaxPayloadBytes.

Always exits 0 and prints problems to stderr, so a failure here can never
break your slicer's export. Works on Windows PowerShell 5.1 and PowerShell 7.
#>

$ErrorActionPreference = "Continue"

$Version = "1.1.0"
$DefaultBaseUrl = "https://3dfilamentprofiles.com"

# Kept in sync with 3dfp-print-log.py and the regexes in
# src/app/[locale]/my/print/parseGCodeFilaments.ts. Order matters for the output.
$LinePrefixes = @(
  "; filament used [g]",
  "; filament used [mm]",
  "; total filament weight [g]",
  "; total filament length [mm]",
  "; total filament used [g]",
  "; filament:",
  "; filament_type =",
  "; filament_vendor =",
  "; filament_colour =",
  "; filament_settings_id =",
  "; printer_model =",
  "; printer_settings_id =",
  "; estimated printing time",
  "; model printing time",
  "; generated by",
  "; BambuStudio",
  "; OrcaSlicer",
  "; PrusaSlicer"
)

$EnvConfigKeys = @(
  "filament_type",
  "filament_vendor",
  "filament_colour",
  "filament_settings_id",
  "printer_model",
  "printer_settings_id"
)

$MaxLineLength = 400
$MaxPayloadBytes = 16 * 1024
$DialogTimeoutSeconds = 60
# Longer than the dialog timeout: a slicer that runs the script again only after the
# first run's dialog closes still lands inside the window.
$DedupeWindowSeconds = 120

function Write-Stderr([string] $Message) {
  [Console]::Error.WriteLine("3dfp-print-log: $Message")
}

function Limit-Length([string] $Value, [int] $Max) {
  if ($Value.Length -gt $Max) { return $Value.Substring(0, $Max) }
  return $Value
}

function Get-LinesFromEnv {
  # Rebuilds '; key = value' config lines from SLIC3R_* env vars, when the slicer set them.
  $found = @{}
  foreach ($key in $EnvConfigKeys) {
    $value = [Environment]::GetEnvironmentVariable("SLIC3R_" + $key.ToUpperInvariant())
    if ($value) { $found["; $key ="] = Limit-Length "; $key = $value" $MaxLineLength }
  }
  return $found
}

function Get-GcodeLines([string] $GcodePath) {
  # Keeps the first line matching each allow-listed prefix, truncated to $MaxLineLength.
  $found = Get-LinesFromEnv
  $haveEnvConfig = $found.Count -gt 0
  $reader = New-Object System.IO.StreamReader($GcodePath, [System.Text.Encoding]::UTF8)
  try {
    while ($null -ne ($line = $reader.ReadLine())) {
      foreach ($prefix in $LinePrefixes) {
        if ($found.ContainsKey($prefix)) { continue }
        if ($line.StartsWith($prefix)) { $found[$prefix] = Limit-Length $line $MaxLineLength }
      }
      if ($found.Count -eq $LinePrefixes.Count) { break }
      # With config from the environment, only the header matters. Bambu Studio and
      # OrcaSlicer put the usage summary in the header block; PrusaSlicer puts it at
      # the end, so only stop early once a weight line has actually been seen.
      if ($haveEnvConfig -and $line.StartsWith("; HEADER_BLOCK_END") -and
          ($found.ContainsKey("; filament used [g]") -or $found.ContainsKey("; total filament weight [g]"))) {
        break
      }
    }
  } finally {
    $reader.Dispose()
  }
  $result = @()
  foreach ($prefix in $LinePrefixes) {
    if ($found.ContainsKey($prefix)) { $result += $found[$prefix] }
  }
  return ,$result
}

function Find-BambuProject([string] $GcodePath) {
  # Bambu Studio slices into a temp project folder and hands us a throwaway path like
  # <tmp>/bamboo_model/<date>/<time#pid#n>/Metadata/.<pid>.<n>.gcode. That folder holds:
  #   - origin.txt: the path of the 3MF the user actually opened (the real project name)
  #   - .3mf: an autosave whose Metadata/model_settings.config lists the plates
  #     (plater_id, plater_name) and maps each to its temp gcode_file.
  $info = @{ ProjectName = $null; PlateIndex = $null; PlateName = $null; Plates = @() }
  $folder = Split-Path -Parent ([System.IO.Path]::GetFullPath($GcodePath))
  $originTxt = $null
  for ($i = 0; $i -lt 3; $i++) {
    $candidate = Join-Path $folder "origin.txt"
    if (Test-Path -LiteralPath $candidate -PathType Leaf) { $originTxt = $candidate; break }
    $parent = Split-Path -Parent $folder
    if (-not $parent -or $parent -eq $folder) { return $info }
    $folder = $parent
  }
  if (-not $originTxt) { return $info }

  try {
    $originPath = ([System.IO.File]::ReadAllText($originTxt, [System.Text.Encoding]::UTF8)).Trim()
    $name = Split-Path -Leaf $originPath
    if ($name) { $info.ProjectName = $name }
  } catch { }

  $autosave = Join-Path $folder ".3mf"
  if (Test-Path -LiteralPath $autosave -PathType Leaf) {
    try {
      Add-Type -AssemblyName System.IO.Compression.FileSystem
      $archive = [System.IO.Compression.ZipFile]::OpenRead($autosave)
      try {
        $entry = $archive.GetEntry("Metadata/model_settings.config")
        $stream = $entry.Open()
        try {
          $settings = (New-Object System.IO.StreamReader($stream, [System.Text.Encoding]::UTF8)).ReadToEnd()
        } finally { $stream.Dispose() }
      } finally { $archive.Dispose() }
      $wanted = Split-Path -Leaf $GcodePath
      foreach ($plateMatch in [regex]::Matches($settings, "<plate>(.*?)</plate>", "Singleline")) {
        $block = $plateMatch.Groups[1].Value
        $plateId = [regex]::Match($block, 'key="plater_id" value="([^"]*)"')
        if (-not $plateId.Success) { continue }
        $nameMatch = [regex]::Match($block, 'key="plater_name" value="([^"]*)"')
        $plateName = if ($nameMatch.Success) { $nameMatch.Groups[1].Value } else { "" }
        $info.Plates += ,@($plateId.Groups[1].Value, $plateName)
        $gcodeFile = [regex]::Match($block, 'key="gcode_file" value="([^"]*)"')
        if ($gcodeFile.Success -and (Split-Path -Leaf $gcodeFile.Groups[1].Value) -eq $wanted) {
          $info.PlateIndex = $plateId.Groups[1].Value
          if ($plateName) { $info.PlateName = $plateName }
        }
      }
    } catch {
      Write-Stderr "could not read plate info: $($_.Exception.Message)"
    }
  }
  return $info
}

function Get-TotalGrams([string[]] $Lines) {
  # Sums the per-filament weights from the usage line, for the confirmation dialog only.
  foreach ($line in $Lines) {
    $match = [regex]::Match($line, "^; (?:total filament weight \[g\] :|filament used \[g\] =) ([\d.,\s]+)$")
    if ($match.Success) {
      $total = 0.0
      foreach ($part in $match.Groups[1].Value.Split(",")) {
        if ($part.Trim()) {
          $parsed = 0.0
          if ([double]::TryParse($part.Trim(), [System.Globalization.NumberStyles]::Float, [System.Globalization.CultureInfo]::InvariantCulture, [ref] $parsed)) {
            $total += $parsed
          } else { return $null }
        }
      }
      return $total
    }
  }
  return $null
}

function ConvertTo-QueryValue([string] $Value) {
  return [Uri]::EscapeDataString($Value)
}

function Build-Url([string] $BaseUrl, [string] $GcodePath) {
  # Returns @(url, summary). url is $null when there is nothing to log.
  $lines = Get-GcodeLines $GcodePath
  if ($lines.Count -eq 0) {
    Write-Stderr "no recognizable filament usage comments found, skipping."
    return @($null, "")
  }

  $payload = [System.Text.Encoding]::UTF8.GetBytes(($lines -join "`n"))
  if ($payload.Length -gt $MaxPayloadBytes) { $payload = $payload[0..($MaxPayloadBytes - 1)] }
  $encoded = [Convert]::ToBase64String($payload).TrimEnd("=").Replace("+", "-").Replace("/", "_")

  $project = Find-BambuProject $GcodePath
  $fileName = if ($project.ProjectName) { $project.ProjectName } else { Split-Path -Leaf $GcodePath }

  $query = "v=1&f=" + (ConvertTo-QueryValue $fileName)
  if ($project.PlateIndex) {
    $query += "&p=" + (ConvertTo-QueryValue $project.PlateIndex)
    if ($project.PlateName) { $query += "&pn=" + (ConvertTo-QueryValue $project.PlateName) }
  } elseif ($project.Plates.Count -gt 0) {
    $plateList = @()
    foreach ($plate in ($project.Plates | Select-Object -First 20)) { $plateList += "$($plate[0]):$($plate[1])" }
    $query += "&pl=" + (ConvertTo-QueryValue ($plateList -join "|"))
  }
  $query += "&d=$encoded"

  $summary = $fileName
  if ($project.PlateIndex) {
    $summary += ", plate $($project.PlateIndex)"
    if ($project.PlateName) { $summary += " ($($project.PlateName))" }
  }
  $grams = Get-TotalGrams $lines
  if ($null -ne $grams) { $summary += ", " + $grams.ToString("0.0", [System.Globalization.CultureInfo]::InvariantCulture) + " g" }

  return @(($BaseUrl.TrimEnd("/") + "/my/print/log?$query"), $summary)
}

function Test-AlreadyHandled([string] $Url) {
  # True when this exact URL was already handled within $DedupeWindowSeconds. Some slicers
  # (Anycubic Slicer NEXT) run post-processing scripts several times for one slice; keying
  # on the URL rather than the gcode path catches that whatever temp file each run is handed.
  # A marker file per URL in the temp folder, created atomically, lets exactly one run
  # through even when the runs overlap. Any file-system trouble means "not handled", so the
  # worst case is the old behaviour: an extra dialog.
  try {
    $tempDir = [System.IO.Path]::GetTempPath()
    $now = Get-Date
    foreach ($stale in Get-ChildItem -Path $tempDir -Filter "3dfp-print-log-*.seen" -File -ErrorAction SilentlyContinue) {
      if (($now - $stale.LastWriteTime).TotalSeconds -gt $DedupeWindowSeconds) {
        Remove-Item -LiteralPath $stale.FullName -Force -ErrorAction SilentlyContinue
      }
    }
    $sha1 = [System.Security.Cryptography.SHA1]::Create()
    try {
      $hash = $sha1.ComputeHash([System.Text.Encoding]::UTF8.GetBytes($Url))
    } finally {
      $sha1.Dispose()
    }
    $digest = ([System.BitConverter]::ToString($hash) -replace "-", "").Substring(0, 16).ToLowerInvariant()
    $marker = Join-Path $tempDir "3dfp-print-log-$digest.seen"
    try {
      # CreateNew fails when the file exists, so overlapping runs cannot both win.
      ([System.IO.File]::Open($marker, [System.IO.FileMode]::CreateNew)).Dispose()
      return $false
    } catch {
      return [System.IO.File]::Exists($marker)
    }
  } catch {
    return $false
  }
}

function Confirm-Log([string] $Summary) {
  # Native yes/no dialog with a timeout, no extra assemblies. Timeout or any failure counts
  # as "yes" so an unattended slice still opens a tab instead of silently dropping the print.
  try {
    $shell = New-Object -ComObject WScript.Shell
    # 4 = Yes/No, 32 = question icon, 4096 = system modal (stays on top). 6 = Yes, -1 = timed out.
    $answer = $shell.Popup("Log this print?`n`n$Summary", $DialogTimeoutSeconds, "3D Filament Profiles", 4 + 32 + 4096)
    return ($answer -eq 6 -or $answer -eq -1)
  } catch {
    Write-Stderr "dialog failed, opening browser anyway: $($_.Exception.Message)"
    return $true
  }
}

function Write-DebugDump([string[]] $Argv, [string] $GcodePath) {
  $dumpPath = Join-Path ([Environment]::GetFolderPath("UserProfile")) "3dfp-print-log-debug.txt"
  $out = New-Object System.Text.StringBuilder
  [void] $out.AppendLine("3dfp-print-log $Version (PowerShell $($PSVersionTable.PSVersion))")
  [void] $out.AppendLine("argv: $($Argv -join ' | ')")
  [void] $out.AppendLine("cwd: $((Get-Location).Path)")
  [void] $out.AppendLine("")
  [void] $out.AppendLine("== env ==")
  foreach ($entry in (Get-ChildItem Env: | Sort-Object Name)) {
    $upper = $entry.Name.ToUpperInvariant()
    if ($upper.StartsWith("SLIC3R") -or $upper.StartsWith("BAMBU") -or $upper.StartsWith("ORCA") -or $upper.StartsWith("PRUSA")) {
      [void] $out.AppendLine("$($entry.Name)=" + (Limit-Length $entry.Value 400))
    }
  }
  [void] $out.AppendLine("")
  [void] $out.AppendLine("== gcode comment lines (first 60 + config block keys) ==")
  try {
    $commentLines = @()
    $configKeys = @()
    $inConfig = $false
    $reader = New-Object System.IO.StreamReader($GcodePath, [System.Text.Encoding]::UTF8)
    try {
      while ($null -ne ($line = $reader.ReadLine())) {
        if ($line.StartsWith("; CONFIG_BLOCK_START")) { $inConfig = $true }
        if ($inConfig -and $line.StartsWith("; ") -and $line.Contains(" = ")) {
          $configKeys += $line.Substring(2).Split(@(" = "), 2, [StringSplitOptions]::None)[0]
        } elseif ($line.StartsWith(";") -and $commentLines.Count -lt 60) {
          $commentLines += Limit-Length $line 300
        }
      }
    } finally { $reader.Dispose() }
    [void] $out.AppendLine($commentLines -join "`n")
    [void] $out.AppendLine("")
    [void] $out.AppendLine("== config keys ==")
    [void] $out.AppendLine($configKeys -join ", ")
  } catch {
    [void] $out.AppendLine("could not read gcode: $($_.Exception.Message)")
  }
  [System.IO.File]::WriteAllText($dumpPath, $out.ToString(), (New-Object System.Text.UTF8Encoding($false)))
  Write-Stderr "debug dump written to $dumpPath"
}

function Main([string[]] $Argv) {
  # Slicers append the gcode path as the LAST argument, so any options can be written
  # before it on the slicer's post-processing line.
  $baseUrl = [Environment]::GetEnvironmentVariable("FILAMENT_PROFILES_URL")
  if (-not $baseUrl) { $baseUrl = $DefaultBaseUrl }
  $dryRun = $false
  $debug = $false
  $ask = $true
  $rest = @()
  $i = 0
  while ($i -lt $Argv.Count) {
    $arg = $Argv[$i]
    $i++
    switch ($arg) {
      "--dry-run" { $dryRun = $true }
      "--debug" { $debug = $true }
      "--no-ask" { $ask = $false }
      "--base-url" { if ($i -lt $Argv.Count) { $baseUrl = $Argv[$i]; $i++ } }
      default { $rest += $arg }
    }
  }

  if ($rest.Count -eq 0) {
    Write-Stderr "no gcode file given, skipping."
    return
  }

  $gcodePath = $rest[$rest.Count - 1]
  if ($debug) {
    try { Write-DebugDump $Argv $gcodePath } catch { Write-Stderr "debug dump failed: $($_.Exception.Message)" }
  }

  try {
    $built = Build-Url $baseUrl $gcodePath
  } catch {
    Write-Stderr "could not read '$gcodePath': $($_.Exception.Message)"
    return
  }
  $url = $built[0]
  $summary = $built[1]
  if (-not $url) { return }

  if ($dryRun) {
    [Console]::Out.WriteLine($url)
    return
  }

  if (Test-AlreadyHandled $url) {
    Write-Stderr "this print was already handled a moment ago, skipping."
    return
  }

  if ($ask -and -not (Confirm-Log $summary)) { return }

  try {
    Start-Process $url
  } catch {
    Write-Stderr "could not open browser: $($_.Exception.Message)"
  }
}

try {
  Main $args
} catch {
  Write-Stderr "unexpected error: $($_.Exception.Message)"
}
exit 0
